[book]
title = "How To Make a Very Serious Game With Javascript"
authors = ["Tiuna Angelini"]
language = "en"

[output.html]
default-theme = "rust" # Opzioni: "light", "rust", "coal", "navy", "ayu"
preferred-dark-theme = "coal"
